connector:
  - id: metronome
    type: metronome
    config:
      interval: 1000

  - id: tcp
    type: tcp
    codec: string
    config:
      port: 4242
      host: "127.0.0.1"

  - id: stdout
    type: stdout
    codec: json
    config:
      prefix: ">> "

binding:
  - id: default
    links:
      '/connector/tcp/{instance}/out':
       - '/pipeline/main/{instance}/in'
      '/connector/metronome/{instance}/out':
       - '/pipeline/main/{instance}/in'
      '/connector/main/{instance}/out':
       - '/connector/stdout/{instance}/in'

mapping:
  /binding/default/01:
    instance: "01"
