[package]
authors = ["The Tremor Team"]
description = "Tremor Script Interpreter"
documentation = "https://docs.rs/tremor-script"
edition = "2021"
license = "Apache-2.0"
name = "tremor-value"
readme = "README.md"
repository = "https://github.com/tremor-rs/tremor-runtime"
version = "0.12.4"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
abi_stable = { version = "0.11.0", default_features = false, features = ["rust_latest_stable"] }
base64 = "0.13"
beef = "0.5"
halfbrown = { version = "0.1.15", features = ["fxhash"] }
serde = "1.0"
simd-json = "0.5"
simd-json-derive = { version = "0.3", features = ["impl-abi_stable"] }
value-trait = { version = "0.2.12", features = ["custom-types", "c-abi"] }

tremor-common = { version = "0.12.0-rc.9", path = "../tremor-common" }

[dev-dependencies]
float-cmp = "0.9"
getopts = "0.2"
proptest = "1.0"
serde = { version = "1", features = ["derive"] }
serde_json = "1"

[features]
128bit = []
